package lof.ui.game;

import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import lof.model.Board;
import lof.model.Player;

/**
 *
 * @author Diego
 */
public class GameInfo extends javax.swing.JPanel {

    private Player you;
    private Player enemy;
    private Board board;
    /**
     * Creates new form GameInfo
     */
    public GameInfo(Board board) {
        this.you = board.getPlayer(0);
        this.enemy = board.getPlayer(1);
        this.board = board;
        initComponents();
        turnInfo.setVisible(true);
        
        
        PropertyChangeListener listener = (PropertyChangeEvent evt) -> {
            if(evt.getPropertyName().equals(Player.PROP_BOXCOUNT)) {
                updatePoints();
            }
        };
        you.addPropertyChangeListener(listener);
        enemy.addPropertyChangeListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlayer1 = new javax.swing.JTextField();
        youPoint = new javax.swing.JTextField();
        jPlayer2 = new javax.swing.JTextField();
        enemyPoint = new javax.swing.JTextField();
        turnInfo = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(170, 97));
        setMinimumSize(new java.awt.Dimension(170, 97));

        jPlayer1.setEditable(false);
        jPlayer1.setBackground(new java.awt.Color(255, 0, 0));
        jPlayer1.setText("You");
        jPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayer1ActionPerformed(evt);
            }
        });

        youPoint.setEditable(false);
        youPoint.setBackground(new java.awt.Color(255, 0, 0));
        youPoint.setText("0");

        jPlayer2.setEditable(false);
        jPlayer2.setBackground(new java.awt.Color(0, 0, 255));
        jPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        jPlayer2.setText("Enemy");
        jPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayer2ActionPerformed(evt);
            }
        });

        enemyPoint.setEditable(false);
        enemyPoint.setBackground(new java.awt.Color(0, 0, 255));
        enemyPoint.setForeground(new java.awt.Color(255, 255, 255));
        enemyPoint.setText("0");

        turnInfo.setEditable(false);
        turnInfo.setBackground(new java.awt.Color(255, 255, 255));
        turnInfo.setText("TurnInfo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turnInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(youPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enemyPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(youPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enemyPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlayer1ActionPerformed

    private void jPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlayer2ActionPerformed

    public void setEnemy(){
        turnInfo.setText("Enemy's turn!");
        turnInfo.setForeground(Color.white);
        turnInfo.setBackground(Color.blue);
    }
    
    public void setYou(){
        turnInfo.setText("Your turn!");
        turnInfo.setForeground(Color.black);
        turnInfo.setBackground(Color.red);
    }

    public void updatePoints(){
        youPoint.setText("" + you.getBoxCount());
        enemyPoint.setText("" + enemy.getBoxCount());
        if(board.isBoardFull()){
            turnInfo.setText("You win!");
            turnInfo.setFont(new java.awt.Font("Tahoma", 1, 24));
            turnInfo.setForeground(Color.black);
            turnInfo.setBackground(Color.red);
            if(you.getBoxCount()<enemy.getBoxCount()){
                turnInfo.setText("Enemy wins!");
                turnInfo.setForeground(Color.white);
                turnInfo.setBackground(Color.blue);
            }   
        }
        java.awt.EventQueue.invokeLater(() -> repaint());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enemyPoint;
    private javax.swing.JTextField jPlayer1;
    private javax.swing.JTextField jPlayer2;
    private javax.swing.JTextField turnInfo;
    private javax.swing.JTextField youPoint;
    // End of variables declaration//GEN-END:variables
}
